
default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  <<: *default
  database: chat_production
  username: chat
  password: <%= ENV['CHAT_DATABASE_PASSWORD'] %>
