# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957b897c61a6e34fbfa10f6d6780bed18927ec030d4c1236e22d8e22092c18e3e5739b91e6df9a7bb47bd007cb597fe7341ed58f16a2dda62fc3cd78a4e129d7

test:
  secret_key_base: f63cd43b67020d316d45957435c0fd2e4ec469177ea40d1a300fb681cac66e298aac55f10dce2ba7cf3d4a582a83f4b92f6fe555c19caf875fac1d2a5886fc48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
